
import "./globals.css";
// import "slick-carousel/slick/slick.css";
// import "slick-carousel/slick/slick-theme.css";
import ScrollToTop from "@/app/components/ScrollToTop";
import { CartProvider } from "./context/CartProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";
// import { YandexMetrika } from "@koiztech/next-yandex-metrika";
import GoogleAnalytics from './components/GoogleAnalytics';
import LayoutClient from './components/LayoutClient'


// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  // const yandexMetrikaId = 101262687;
  // const googleAnalytics = 101262687;
  return (
    <html lang="ru">
      <meta charSet="utf-8" />
      <link rel="icon" href="/favicon.ico" sizes="any" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <title>strikeops</title>
      <meta name="description" content='Магазин страйкбольной пиротехники: Гранаты, дымы, мины-растяжки, армейская пиротехника' />

      <body >

        <div>
          <ScrollToTop />
          {/* <YandexMetrika
            id={process.env.NEXT_PUBLIC_YANDEX_ID}
            clickmap={true}
            trackLinks={true}
            accurateTrackBounce={true}
            webvisor={true}
            strategy="afterInteractive" /> */}

          <GoogleAnalytics ga_id={process.env.NEXT_PUBLIC_GOOGLE_ANALYTICS} />
          <CartProvider>
            <Header />

            <LayoutClient > 
              {children}
            </LayoutClient>
            <Footer />

          </CartProvider>

        </div>
      </body>
    </html >
  );
}
