import { Inter } from "next/font/google";
import "./globals.css";

import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import { CartProvider } from "./context/CartProvider";
import Header from "./components/Header";
import Footer from "./components/Footer";

// const inter = Inter({ subsets: ["latin"] }); className={inter.className}

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body >
        <div>

          <CartProvider>
            <Header />
            {children}
            <Footer />

          </CartProvider>
        </div>

      </body>
    </html>
  );
}
